name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 默认分支

# 设置 GITHUB_TOKEN 的权限
permissions:
  contents: read
  pages: write
  id-token: write

# 允许一个并发部署
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create necessary directories
        run: |
          mkdir -p .intlayer/main
          mkdir -p .intlayer/dictionary
          mkdir -p src/locales

      - name: Copy Intlayer files
        run: |
          cp -r .intlayer/* .intlayer/ || true
          ls -la .intlayer/

      - name: Build Intlayer configuration
        run: |
          echo "Running Intlayer build..."
          NODE_ENV=production npm run intlayer:build
          echo "Checking generated files:"
          ls -la .intlayer/
          ls -la src/locales/

      - name: Copy dictionary files
        run: |
          cp -r src/locales/* .intlayer/dictionary/ || true
          ls -la .intlayer/dictionary/

      - name: Build project
        run: |
          echo "Starting project build..."
          NODE_ENV=production npm run build
          echo "Checking build output:"
          ls -la dist/

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 