name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 默认分支

# 设置 GITHUB_TOKEN 的权限
permissions:
  contents: read
  pages: write
  id-token: write

# 允许一个并发部署
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create necessary directories and files
        run: |
          # 创建所有必要的目录
          mkdir -p .intlayer/dictionary
          mkdir -p .intlayer/main
          mkdir -p .intlayer/cache
          mkdir -p .intlayer/config
          mkdir -p .intlayer/types
          
          # 创建 dictionaries.cjs 文件
          cat > .intlayer/main/dictionaries.cjs << 'EOL'
          module.exports = {
            "app": require("../dictionary/app.json")
          };
          EOL
          
          # 创建 app.json 文件
          cat > .intlayer/dictionary/app.json << 'EOL'
          {
            "key": "app",
            "content": {
              "nav": {
                "home": {
                  "nodeType": "translation",
                  "translation": {
                    "zh-Hans": "首页",
                    "en": "Home",
                    "ja": "ホーム"
                  }
                },
                "articles": {
                  "nodeType": "translation",
                  "translation": {
                    "zh-Hans": "文章",
                    "en": "Articles",
                    "ja": "記事"
                  }
                }
              }
            }
          }
          EOL
          
          # 创建 configuration.json 文件
          cat > .intlayer/config/configuration.json << 'EOL'
          {
            "internationalization": {
              "locales": ["zh-Hans", "en", "ja"],
              "defaultLocale": "zh-Hans"
            }
          }
          EOL
          
          # 设置文件权限
          chmod 644 .intlayer/main/dictionaries.cjs
          chmod 644 .intlayer/dictionary/app.json
          chmod 644 .intlayer/config/configuration.json
          
          # 显示创建的文件
          echo "Created files:"
          ls -la .intlayer/main/
          ls -la .intlayer/dictionary/
          ls -la .intlayer/config/
          
          echo "Content of dictionaries.cjs:"
          cat .intlayer/main/dictionaries.cjs
          
          echo "Content of app.json:"
          cat .intlayer/dictionary/app.json
          
          echo "Content of configuration.json:"
          cat .intlayer/config/configuration.json

      - name: Build project
        run: |
          echo "Starting intlayer build..."
          npm run intlayer:build
          echo "Starting project build..."
          NODE_ENV=production VITE_APP_ENV=production npm run build
          echo "Checking build output:"
          ls -la dist/

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 